---
area/docker:
  - changed-files:
      - any-glob-to-any-file: ".dockerignore"
      - any-glob-to-any-file: "Dockerfile"

area/github:
  - changed-files:
      - any-glob-to-any-file: ".github/**/*"

area/go:
  - changed-files:
      - any-glob-to-any-file: "cmd/**/*"
      - any-glob-to-any-file: "internal/**/*"
      - any-glob-to-any-file: "pkg/**/*"
      - any-glob-to-any-file: "go.mod"
      - any-glob-to-any-file: "go.sum"
