---
# yaml-language-server: $schema=https://goreleaser.com/static/schema.json
version: 2
project_name: external-dns-provider-mikrotik

before:
  hooks:
    - go mod tidy
    - go mod download
builds:
  - env:
      - CGO_ENABLED=0
    binary: "{{.ProjectName}}"
    goos:
      - linux
      - darwin
    ldflags:
      - -s -w
      - -X github.com/mirceanton/{{.ProjectName}}/cmd.Version={{.Version}}
      - -X github.com/mirceanton/{{.ProjectName}}/cmd.Gitsha={{.ShortCommit}}

archives:
  - format: tar.gz
    name_template: "{{.ProjectName}}_{{.Os}}_{{.Arch}}"

checksum:
  disable: false
  name_template: "checksums.txt"

changelog:
  disable: false
  use: github
  sort: asc
  groups:
    - title: Features
      regexp: '^.*?feat(\([[:word:]]+\))??!?:.+$'
      order: 0
    - title: "Patches"
      regexp: '^.*?fix(\([[:word:]]+\))??!?:.+$'
      order: 1
    - title: "CI"
      regexp: ".*ci.*"
      order: 998
    - title: Others
      order: 999

dockers:
  - image_templates:
      - "ghcr.io/mirceanton/{{.ProjectName}}:v{{.Version}}-amd64"
    use: buildx
    dockerfile: Dockerfile
    build_flag_templates:
      - "--platform=linux/amd64"
      - "--label=org.opencontainers.image.created={{.Date}}"
      - "--label=org.opencontainers.image.title={{.ProjectName}}"
      - "--label=org.opencontainers.image.revision={{.FullCommit}}"
      - "--label=org.opencontainers.image.version={{.Version}}"
      - "--label=org.opencontainers.image.url=https://github.com/mirceanton/{{.ProjectName}}"
      - "--label=org.opencontainers.image.source=https://github.com/mirceanton/{{.ProjectName}}"
      - "--label=org.opencontainers.image.licenses=Apache License 2.0"
      - "--label=org.opencontainers.image.authors=Mircea-Pavel Anton <contact@mirceanton.com>"
      - "--label=org.opencontainers.image.description=ExternalDNS webhook to manage Mikrotik DNS Records."
  - image_templates:
      - "ghcr.io/mirceanton/{{.ProjectName}}:v{{.Version}}-arm64v8"
    use: buildx
    goarch: arm64
    dockerfile: Dockerfile
    build_flag_templates:
      - "--platform=linux/arm64/v8"
      - "--label=org.opencontainers.image.created={{.Date}}"
      - "--label=org.opencontainers.image.title={{.ProjectName}}"
      - "--label=org.opencontainers.image.revision={{.FullCommit}}"
      - "--label=org.opencontainers.image.version={{.Version}}"
      - "--label=org.opencontainers.image.url=https://github.com/mirceanton/{{.ProjectName}}"
      - "--label=org.opencontainers.image.source=https://github.com/mirceanton/{{.ProjectName}}"
      - "--label=org.opencontainers.image.licenses=Apache License 2.0"
      - "--label=org.opencontainers.image.authors=Mircea-Pavel Anton <contact@mirceanton.com>"
      - "--label=org.opencontainers.image.description=ExternalDNS webhook to manage Mikrotik DNS Records."

docker_manifests:
  - name_template: "ghcr.io/mirceanton/{{.ProjectName}}:v{{.Version}}"
    image_templates:
      - "ghcr.io/mirceanton/{{.ProjectName}}:v{{.Version}}-amd64"
      - "ghcr.io/mirceanton/{{.ProjectName}}:v{{.Version}}-arm64v8"

  - name_template: "ghcr.io/mirceanton/{{.ProjectName}}:latest"
    image_templates:
      - "ghcr.io/mirceanton/{{.ProjectName}}:v{{.Version}}-amd64"
      - "ghcr.io/mirceanton/{{.ProjectName}}:v{{.Version}}-arm64v8"
