---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
spec:
  replicas: 3 # Number of desired pods
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
        - name: nginx
          image: nginx:latest
          ports:
            - containerPort: 80

---
apiVersion: v1
kind: Service
metadata:
  name: nginx-service
spec:
  selector:
    app: nginx
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: ClusterIP

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: nginx-demo
  annotations:
    external-dns.alpha.kubernetes.io/hostname: "example.com"
    external-dns.alpha.kubernetes.io/cloudflare-proxied: "false" # ? test for unknown PS configuration
    # external-dns.alpha.kubernetes.io/ttl: "`60" # ? Test for default ttl
    # external-dns.alpha.kubernetes.io/webhook-comment: "This is a static DNS record created via ingress annotations!" # ? test for default comment
    external-dns.alpha.kubernetes.io/webhook-address-list: "4.5.6.7"
    external-dns.alpha.kubernetes.io/webhook-match-subdomain: "false"
    external-dns.alpha.kubernetes.io/webhook-disabled: "false"
spec:
  rules:
    - host: example.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: nginx-service
                port:
                  number: 80
