---
# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
name: Goreleaser
permissions: { contents: read }

on:
  push:
    tags: ["v*"]

jobs:
  goreleaser:
    if: github.repository_owner == 'mirceanton' # ? don't run on forks -> missing repo secrets
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with: { fetch-depth: 0 }

      - name: Setup mise
        uses: jdx/mise-action@c1ecc8f748cd28cdeabf76dab3cccde4ce692fe4 # v4.0.0

      - name: Generate Token
        uses: actions/create-github-app-token@f8d387b68d61c58ab83c6c016672934102569859 # v3.0.0
        id: app-token
        with:
          app-id: "${{ secrets.BOT_APP_ID }}"
          private-key: "${{ secrets.BOT_APP_PRIVATE_KEY }}"

      - name: Login to Container Registry
        uses: docker/login-action@b45d80f862d83dbcd57f89517bcf500b2ab88fb2 # v4.0.0
        with:
          registry: "ghcr.io"
          username: "${{ github.actor }}"
          password: "${{ secrets.GHCR_RW_TOKEN }}"

      - name: Run goreleaser
        run: mise exec -- goreleaser --clean
        env:
          GITHUB_TOKEN: "${{ steps.app-token.outputs.token }}"
          TAP_GITHUB_TOKEN: "${{ secrets.GHCR_RW_TOKEN }}"
