---
# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
name: Goreleaser
permissions: { contents: read }

on:
  push:
    tags: ["v*"]

jobs:
  goreleaser:
    if: github.repository_owner == 'mirceanton' # ? don't run on forks -> missing repo secrets
    runs-on: ubuntu-slim
    steps:
      - name: Checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with: { fetch-depth: 0 }

      - name: Setup mise
        uses: jdx/mise-action@dad1bfd3df957f44999b559dd69dc1671cb4e9ea # v4.2.1

      - name: Generate Token
        uses: actions/create-github-app-token@bcd2ba49218906704ab6c1aa796996da409d3eb1 # v3.2.0
        id: app-token
        with:
          client-id: ${{ secrets.BOT_APP_CLIENT_ID }}
          private-key: "${{ secrets.BOT_APP_PRIVATE_KEY }}"

      - name: Login to Container Registry
        uses: docker/login-action@06fb636fac595d6fb4b28a5dfcb21a6f5091859c # v4.5.0
        with:
          registry: "ghcr.io"
          username: "${{ github.actor }}"
          password: "${{ secrets.GHCR_RW_TOKEN }}"

      - name: Run goreleaser
        run: mise exec -- goreleaser --clean
        env:
          GITHUB_TOKEN: "${{ steps.app-token.outputs.token }}"
          TAP_GITHUB_TOKEN: "${{ secrets.GHCR_RW_TOKEN }}"
