---
# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
name: Lint
permissions: { contents: read }

on:
  workflow_dispatch: {}
  pull_request: { branches: ["main"] }
  push: { branches: ["main", "renovate/**"] }

jobs:
  actionlint:
    runs-on: ubuntu-slim
    steps:
      - name: Checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

      - name: Setup mise
        uses: jdx/mise-action@dad1bfd3df957f44999b559dd69dc1671cb4e9ea # v4.2.1

      - name: Run actionlint
        run: mise exec -- actionlint

  golangci-lint:
    runs-on: ubuntu-slim
    steps:
      - name: Checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

      - name: Setup mise
        uses: jdx/mise-action@dad1bfd3df957f44999b559dd69dc1671cb4e9ea # v4.2.1

      - name: Run golangci-lint
        run: mise exec -- golangci-lint run

  prettier:
    runs-on: ubuntu-slim
    steps:
      - name: Checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

      - name: Setup mise
        uses: jdx/mise-action@dad1bfd3df957f44999b559dd69dc1671cb4e9ea # v4.2.1

      - name: Run prettier
        run: mise exec -- prettier --check .
