---
# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
name: GolangCI Lint

on:
  # Manual Trigger
  workflow_dispatch:
    inputs:
      dry-run:
        description: Dry Run
        required: false
        default: false
        type: boolean

  # Dry Run on any PR that changes the config or the workflow
  pull_request:
    paths:
      - .github/workflows/golangci-lint.yaml
      - .golangci.yaml

jobs:
  golangci:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - name: Generate Token
        uses: actions/create-github-app-token@d72941d797fd3113feb6b93fd0dec494b13a2547 # v1.12.0
        id: app-token
        with:
          app-id: "${{ secrets.BOT_APP_ID }}"
          private-key: "${{ secrets.BOT_APP_PRIVATE_KEY }}"

      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          token: "${{ steps.app-token.outputs.token }}"
          fetch-depth: 0

      - name: Setup Go
        uses: actions/setup-go@v5.4.0
        with: { go-version-file: go.mod }

      - name: Run golangci-lint
        uses: golangci/golangci-lint-action@v7.0.0
        with:
          version: v2.0.2
