---
# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
name: Lint - actionlint

on:
  workflow_dispatch: {}
  pull_request:
    paths:
      - ".github/workflows/**"

jobs:
  github-actions:
    runs-on: ubuntu-latest
    container: ghcr.io/mirceanton/gha-runner-actionlint:latest
    steps:
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Run actionlint
        run: actionlint
