---
# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
name: Lint - markdownlint

on:
  workflow_dispatch: {}

  pull_request:
    paths:
      - "**.md"
      - .github/configs/.markdownlint.yaml

jobs:
  markdownlint:
    runs-on: ubuntu-latest
    container: ghcr.io/mirceanton/gha-runner-markdownlint:latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Run MarkdownLint
        run: markdownlint --config=.github/configs/.markdownlint.yaml "**/*.md"
