---
# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
name: Lint
permissions: { contents: read }

on:
  workflow_dispatch: {}
  pull_request: { branches: ["main"] }
  push: { branches: ["main", "renovate/**"] }

jobs:
  actionlint:
    runs-on: ubuntu-slim
    steps:
      - name: Checkout
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0

      - name: Setup mise
        uses: jdx/mise-action@e6a8b3978addb5a52f2b4cd9d91eafa7f0ab959d # v4.2.0

      - name: Run actionlint
        run: mise exec -- actionlint

  golangci-lint:
    runs-on: ubuntu-slim
    steps:
      - name: Checkout
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0

      - name: Setup mise
        uses: jdx/mise-action@e6a8b3978addb5a52f2b4cd9d91eafa7f0ab959d # v4.2.0

      - name: Run golangci-lint
        run: mise exec -- golangci-lint run

  prettier:
    runs-on: ubuntu-slim
    steps:
      - name: Checkout
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0

      - name: Setup mise
        uses: jdx/mise-action@e6a8b3978addb5a52f2b4cd9d91eafa7f0ab959d # v4.2.0

      - name: Run prettier
        run: mise exec -- prettier --check .
