---
# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
name: Test

on:
  # Manual Trigger
  workflow_dispatch: {}

  # Run on any PR
  pull_request: {}

jobs:
  test:
    uses: mirceanton/reusable-workflows/.github/workflows/reusable-go-test.yaml@f4dce998a168bbe2e53664acf4dd29407cd3d29f # v3.4.19
    secrets: inherit
    with:
      go-version: stable
